package com.tpeapp.tasks

/**
 * Represents a task assigned by the accountability partner to the device owner.
 *
 * @param id          Unique identifier (UUID string) generated by the partner.
 * @param title       Short task title (e.g. "Morning workout").
 * @param description Detailed instructions for completing the task.
 * @param deadlineMs  Epoch milliseconds by which the task must be verified.
 * @param status      Current state of the task.
 * @param photoUri    Absolute path of the proof photo once captured; null until then.
 */
data class Task(
    val id: String,
    val title: String,
    val description: String,
    val deadlineMs: Long,
    val status: TaskStatus,
    val photoUri: String? = null
)

enum class TaskStatus {
    /** Assigned but not yet verified. */
    PENDING,
    /** Verified by the device owner with a photo. */
    COMPLETED,
    /** Deadline passed without verification. */
    MISSED
}
