package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.FlutterPlugin;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";

  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    registerByName(
        flutterEngine,
        "io.flutter.plugins.sharedpreferences.LegacySharedPreferencesPlugin",
        "shared_preferences_android_legacy");
  }

  private static void registerByName(@NonNull FlutterEngine flutterEngine, @NonNull String className, @NonNull String pluginName) {
    try {
      Class<?> clazz = Class.forName(className);
      Object instance = clazz.getDeclaredConstructor().newInstance();
      if (instance instanceof FlutterPlugin plugin) {
        flutterEngine.getPlugins().add(plugin);
      } else {
        Log.e(TAG, "Plugin class is not a FlutterPlugin: " + className);
      }
    } catch (Throwable t) {
      Log.e(TAG, "Error registering plugin " + pluginName + ", " + className, t);
    }
  }
}